### PR TITLE
Main implemented

### LINKED ISSUE #2: Implement main functionality
ACs:
- Should create `EventLoop` instance
- Should read data from input file
- Should parse commands from file and add them to `MessageQueue` or in case of error - throw exception
- Should call AwaitFinish on the end of execution, to wait until all commands won't be executed
- Commands with arguments could be parsed with `parts := strings.Fields(commandLine)`
- Command syntax: `<instruction> <argument> ...`. Instruction and arguments should be separated at least with one space
- Parse input file path from command line arguments

- __Main example:__
```go
eventLoop := new(engine.EventLoop)
eventLoop.Start()
if input, err := os.Open(inputFile); err == nil {
  defer input.Close()
  scanner := bufio.NewScanner(input)
  for scanner.Scan() {
    commandLine := scanner.Text()
    cmd := parse(commandLine) // parse the line to get a Command
    eventLoop.Post(cmd)
  } 
}
eventLoop.AwaitFinish() 
```

- __Valid flow example:__
```
# input file
print hello
mul 5 4
```
```go
// equivalent
eventLoop.Post(&printCommand{arg: “hello”})
eventLoop.Post(&mulCommand{arg1: 5, arg2: 4})
```

- __Invalid flow example:__
```
# input file
mul a 4
```
```go
// equivalent
// <details> err message from strconv.Atoi()
eventLoop.Post(&printCommand{arg: “SYNTAX ERROR: <details>”})
```

### PR DESCRIPTION
**Pull request by lightballer**
Closes #2

### CODE REVIEW

File: cmd/server/main.go [hunk 1]
```diff
@@ -1,9 +1,53 @@
...
+		if len(arr) == 3 {
+			if len(arr[2]) == 1 {
+				r := []rune(arr[2])
+				return &command.Split{Input: arr[1], Separator: r[0]}
+			}
+			return &command.Print{Value: "SYNTAX ERROR: separator should be a single character"}
+		}
+		return &command.Print{Value: "SYNTAX ERROR: invalid arguments count"}
+	}
+	return &command.Print{Value: "SYNTAX ERROR: invalid command"}
```
Comment (yehorbk) [inline cmd/server/main.go:52]: Errors during interpretation should not be putted in the result file. They should be printed to the terminal.

From issue:
> _Should parse commands from file and add them to MessageQueue or **in case of error - throw exception**_

**Review by yehorbk — CHANGES_REQUESTED** [review]

File: cmd/server/main.go (hunk 1 above)
Comment (lightballer) [reply cmd/server/main.go:52]: image

Comment (yehorbk) [reply cmd/server/main.go:52]: 👍

**Review by yehorbk — APPROVED** [review]
